' Simuler emprunt-----------------------------------------------------------------------------------------------------------------------------
@startuml
left to right direction

actor "Chef d'agence" as Chef

Chef --> (Simuler un emprunt)
Chef --> (Simuler une assurance  d'emprunt)

' note right: C'est une bulle de texte


@enduml

' Simuler assurance d'emprunt-----------------------------------------------------------------------------------------------------------------------------
@startuml
left to right direction

actor "Chef d'agence" as Chef

Chef --> (Simuler une assurance  d'emprunt)

' note right: C'est une bulle de texte


@enduml

' Crée un compte-----------------------------------------------------------------------------------------------------------------------------
@startuml
left to right direction

actor "Chef d'agence" as Chef

Chef --> (Créer un compte)
Chef --> (Cloturer un compte)

@enduml

' Créditer/débiter un compte-----------------------------------------------------------------------------------------------------------------------------
@startuml
left to right direction

actor "Guichetier" as Chef

Chef --> (Créditer)
Chef --> (Débiter)
@enduml

' Faire un virement-----------------------------------------------------------------------------------------------------------------------------
@startuml
left to right direction

actor "Guichetier" as Chef

Chef --> (Effectuer un virement de compte a compte)
@enduml