= Cahier De Recette - DailyBankApp
:toc:
:toc-title: Sommaire


= *Page de garde*


[cols="2*"]
|===
| Version | 2

| Date | 24/05/2023

| Équipe | 2B4: +
Loïs Pacqueteau +
Bradley Djedje +
Clement Dejean Gourrié

| Projet | sae2023-bank
|===


:Entreprise: DailyBank
:Equipe:  

 



== I. Introduction
=== 1. Objet :
[.text-justify]
Ce document a été produit dans le cadre d'un projet d'élaboration d'une application bancaire pour ...


== II. Pre-Requis :
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Une base de données installée (référence document technique).
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Les fiches de tests. *À vérifier*


=== 1. Éléments à tester :
[.text-justify]
Les éléments testés concernent les Use-Cases spécifiés dans la *documentation technique*.


=== 2. Environnement de test :
[.text-justify]
Ordinateur sous Windows ou OS équivalent.



== III. Cas de test :
=== 1. Fonctionnalités des guichetiers :
==== 1.1 Gestion des clients :

|====

>|Cas de test 4+|Test-01-01-01
>|Titre 4+|Création d'un nouveau client
>|Objectif 4+| Vérifier qu'il est possible de créer un nouveau client

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur le bouton "Nouveau client". ^|La fenêtre de création des clients s'ouvre. ^| aucune ^|OK
^|All_G_C.2 ^|Compléter les champs spécifiés et valider. ^|Un nouveau client est créé. ^|aucune ^|OK


5+|

5+|Commentaire :
Compléter et si on ne valide pas, ...
|====


|====

>|Cas de test 4+|Test-01-01-02
>|Titre 4+|Modification d'un client
>|Objectif 4+| Vérifier qu'il est possible de modifier un client

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.3 ^|Cliquer sur le bouton "Modifier client". ^|La fenêtre de modification des données du clients s'ouvre. ^|Le client est sélectionné ^|OK
^|All_G_C.4 ^|Modifier les champs souhaités et confirmer. ^|Retour sur les informations du client. Le client est modifié. ^|La fenêtre modifier client est active ^|OK
^|All_G_C.5 ^|Modifier les champs souhaités et annuler. ^|Retour sur les informations du client. Le client est inchangé. ^|La fenêtre modifier client est active ^|OK

|====


|====
>|Cas de test 4+|Test-01-01-03
>|Titre 4+|Suppression d'un client
>|Objectif 4+| Vérifier qu'il est possible de supprimer un client

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.6 ^|Cliquer sur le bouton "Supprimer client". ^|La fenêtre de suppression des données du clients s'ouvre. ^|Le client est sélectionné ^|OK
^|All_G_C.7 ^|Confirmer la suppression. ^|Retour sur la liste des clients. Le client est supprimé. ^|La fenêtre supprimer client est active ^|OK
^|All_G_C.8 ^|Annuler la suppression. ^|Retour sur la liste des clients. Le client est inchangé. ^|La fenêtre supprimer client est active ^|OK

|====


==== 1.2 Gestion des comptes bancaires :


|====

>|Cas de test 4+|Test-01-02-03
>|Titre 4+|Consultation d'un compte
>|Objectif 4+| Vérifier qu'il est possible de consulter un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Comptes client". ^|La page des comptes du client s’affiche. ^|Un client actif est sélectionné ^|OK
^|All_G_CB.2 ^|Sélectionner le bouton "Voir opérations". ^|La page des opérations du compte s’affiche. ^|Un compte actif est sélectionné ^|OK
...

|====


==== 1.3 Gestion des opérations :

|====

>|Cas de test 4+|Test-01-03-01
>|Titre 4+|Débiter un compte
>|Objectif 4+| Vérifier qu'il est possible de débiter un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Enregistrer Débit". ^|La page des débit du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros
 ^|OK
^|All_G_COP.3  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde est -50 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros.
 ^|OK
^|All_G_COP.4  ^|Rentrer un montant 250 dans le champ "Montant". ^|Blocage ! + pop-up ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros.
 ^|OK
  
 

|====

|====

>|Cas de test 4+|Test-01-03-01
>|Titre 4+|Crediter un compte
>|Objectif 4+| Vérifier qu'il est possible de Crediter un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Enregistrer Débit". ^|La page des credit du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +150euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros
 ^|OK

  
|====

==== 1.4 Gestion des comptes bancaires :


|====

>|Cas de test 4+|Test-01-03-01
>|Titre 4+|Crée un compte
>|Objectif 4+| Vérifier qu'il est possible de crée un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Nouveau Compte". ^|La page de creation du compte s’affiche. ^| Aucune ^|OK
^|All_G_COP.2  ^|Rentrer un montant 200 dans le champ "Decouvert autorisé" et 200 dans le champ "Solde" et valider en cliquant "Ajouter". ^|Le nouveau compte crée a un solde de 200euros et un decouvert autorisé de -200. ^|Aucune
 ^|OK

  
|====



|====

>|Cas de test 4+|Test-01-03-01
>|Titre 4+|Cloturer un compte
>|Objectif 4+| Vérifier qu'il est possible de cloturer un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Dans le gestionnaire des comptes cliquer sur un compte. ^|Les boutons "Modifier Compte" et "Supprimer Compte" du compte s’affiche. ^|le client doit au moins avoir un compte non cloturé ^|OK
^|All_G_COP.2  ^|Cliquer sur Supprimmer compte. ^|Une page de confirmation va s'ouvrir ^|Seulement si le compte n'est pas deja cloturé ^|OK
^|All_G_COP.3  ^|Cliquer sur Supprimmer . ^|Le message se ferme est le compte est supprimé ^|Aucune ^|OK

  
|====

==== 1.5 Gestion des prelevements :

|====
>|Cas de test 4+|Test-01-03-01
>|Titre 4+|Crée un prelevement
>|Objectif 4+| Vérifier qu'il est possible de crée un prelevement

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Nouveau Prelevement". ^|La page de creation du prelevement s’affiche. ^| On doit avoir selectionner un compte qui n'est pas cloturer  ^|OK
^|All_G_COP.2  ^|Rentrer le montant 200 dans le champ "Montant" indiquer "Airbus" et 10 dans le champ "Jour de prelevement" et valider en cliquant "Ajouter". ^|Le nouveau prelevement crée a un montant de 200euros avec une date de 10 et un destinataire nommée "Airbus". ^|Le destinataire n'est pas vide le montant est superieur a 0 et le jour de 
prelevement est compris entre 1 et 31  ^|OK

   
|====

|====
>|Cas de test 4+|Test-01-03-01
>|Titre 4+|Modifier un prelevement
>|Objectif 4+| Vérifier qu'il est possible de modifier un prelevement

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Dans le gestionnaire des prelevements cliquer sur un prelevement. ^|Les boutons "Modifier Prelevement" et "Supprimer Prelevement" du prelevement s’affiche. ^|le client doit au moins avoir un prelevement ^|OK
^|All_G_COP.2  ^|Cliquer sur Modifier Prelevement. ^|Une page de modification va s'ouvrir ^|Seulement si le prelevement est selectionner ^|OK
^|All_G_COP.3  ^|Rentrer le montant 20 dans le champ "Montant" indiquer "Airvoiture" et 1 dans le champ "Jour de prelevement" et valider en cliquant "Modifier". ^|Le prelevement est modifié ^|Le destinataire n'est pas vide le montant est superieur a 0 et le jour de
prelevement est compris entre 1 et 31  ^|OK


=== 2. Fonctionnalités des chefs d'agence :
[.text-justify]
Les chefs d'agence ont accès aux mêmes fonctionnalités que les guichetiers, ainsi que d'autres qui leur sont réservées.

==== 2.1 Gestion des clients :

|====

>|Cas de test 4+|Test-02-01-01
>|Titre 4+|Rendre inactif un client
>|Objectif 4+| Vérifier qu'il est possible de rendre un client inactif

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Inactif" et confirmer. ^|...  ^|Un client actif est sélectionné ... ^| ...

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====
