= *Documentation technique V1*
:toc:
:doctype: book
:toc-title: Sommaire
:sectnums:
:Equipe:


= *Page de garde*
[cols="2*"]
|===
| Version | 2

| Date | 24/05/2023

| Équipe | 2B4: +
Loïs Pacqueteau +
Bradley Djedje +
Clement Dejean Gourrié

| Projet | sae2023-bank
|===

== *Présentation de l’Application*
L’application permet de gérer des comptes bancaires de dépôt pour des clients. L’application possède actuellement quelques fonctionnalités tels que modifier les informations clients, créer un nouveau client, consulter un compte, créer un compte, créditer/débiter un compte, effectuer un virement, clôturer un compte, gérer les employés, rendre inactif un client à l’aide des boutons interactifs et des champs à remplir, similer un emprunt, ect...

=== *Use Case*

=== *Diagramme de classe des données global*
* AgenceBancaire : Cette table représente les agences bancaires. Elle contient des informations telles que l'identifiant de l'agence (idAg), le nom de l'agence (nomAg), l'adresse postale de l'agence (adressePostaleAg) et l'identifiant de l'employé chef d'agence (idEmployeChefAg). La contrainte "fk_AgenceBancaire_Emp_ChefAg" définit une relation de clé étrangère entre l'agence bancaire et l'employé qui en est le chef.

* Employe : Cette table représente les employés de l'agence. Elle contient des informations telles que l'identifiant de l'employé (idEmploye), le nom (nom), le prénom (prenom), les droits d'accès (droitsAccess), le login et le mot de passe (login, motPasse), ainsi que l'identifiant de l'agence à laquelle l'employé est rattaché (idAg). La contrainte "fk_Employe_AgenceBancaire" définit une relation de clé étrangère entre l'employé et l'agence bancaire à laquelle il est rattaché.

* Client : Cette table représente les clients de la banque. Elle contient des informations telles que l'identifiant du client (idNumCli), le nom (nom), le prénom (prenom), l'adresse postale (adressePostale), l'adresse e-mail (email), le numéro de téléphone (telephone), le statut d'inactivité (estInactif) et l'identifiant de l'agence à laquelle le client est rattaché (idAg). La contrainte "fk_Client_AgenceBancaire" définit une relation de clé étrangère entre le client et l'agence bancaire à laquelle il est rattaché. La contrainte "ck_Client_estInactif" assure que la valeur du champ "estInactif" est soit 'O' (inactif) ou 'N' (actif).

* CompteCourant : Cette table représente les comptes courants des clients. Elle contient des informations telles que l'identifiant du compte (idNumCompte), le montant du découvert autorisé (debitAutorise), le solde du compte (solde) et l'identifiant du client auquel le compte est associé (idNumCli). La contrainte "fk_CpteCourant_Client" définit une relation de clé étrangère entre le compte courant et le client auquel il est associé.

* TypeOperation : Cette table représente les types d'opérations possibles. Elle contient uniquement l'identifiant du type d'opération (idTypeOp).

* Operation : Cette table représente les opérations effectuées sur les comptes. Elle contient des informations telles que l'identifiant de l'opération (idOperation), le montant de l'opération (montant), la date de l'opération (dateOp), la date de valeur de l'opération (dateValeur), l'identifiant from output d'opération (idTypeOp) qui indique le type d'opération effectuée, l'identifiant du compte sur lequel l'opération a été effectuée (idNumCompte), ainsi que l'identifiant de l'employé ayant effectué l'opération (idEmploye).

* TypeCompte : Cette table représente les différents types de compte disponibles. Elle contient des informations telles que l'identifiant du type de compte (idTypeCompte) et la description du type de compte (description).

* CompteEpargne : Cette table représente les comptes d'épargne des clients. Elle contient des informations similaires à la table CompteCourant, telles que l'identifiant du compte (idNumCompte), le solde du compte (solde) et l'identifiant du client auquel le compte est associé (idNumCli).

* Les flèches entre les différentes tables représentent les relations entre elles. Par exemple, la relation entre AgenceBancaire et Employe indique que chaque agence peut avoir plusieurs employés, tandis que la relation entre Client et AgenceBancaire indique que chaque client est rattaché à une agence spécifique.

* En résumé, ce diagramme de classe des données représente la structure de la base de données du système bancaire, en détaillant les tables et les relations entre elles. Il offre une vision globale des entités et de leurs attributs, permettant de gérer les informations relatives aux agences, aux employés, aux clients, aux comptes courants et d'épargne, ainsi qu'aux opérations bancaires.

== *Architecture*

=== *Architecture générale*

=== *Fonctionnalité*

